documentation:
  - docs/**/*

"topic: Audio":
  - src/torchmetrics/audio/*
  - src/torchmetrics/functional/audio/*

"topic: Classif":
  - src/torchmetrics/classification/*
  - src/torchmetrics/functional/classification/*

"topic: Cluster":
  - src/torchmetrics/clustering/*
  - src/torchmetrics/functional/clustering/*

"topic: Detect":
  - src/torchmetrics/detection/*
  - src/torchmetrics/functional/detection/*

"topic: Image":
  - src/torchmetrics/image/*
  - src/torchmetrics/functional/image/*

"topic: MModal":
  - src/torchmetrics/multimodal/*
  - src/torchmetrics/functional/multimodal/*

"topic: Nominal":
  - src/torchmetrics/nominal/*
  - src/torchmetrics/functional/nominal/*

"topic: Regress":
  - src/torchmetrics/regression/*
  - src/torchmetrics/functional/regression/*

"topic: Retrieval":
  - src/torchmetrics/retrieval/*
  - src/torchmetrics/functional/retrieval/*

"topic: Text":
  - src/torchmetrics/text/*
  - src/torchmetrics/functional/text/*
