name: Unittesting and coverage
description: pull data samples -> unittests

inputs:
  python-version:
    description: Python version
    required: true
  pytorch-version:
    description: PyTorch version
    required: true
  requires:
    description: define oldest or latest
    required: false
    default: ""
  dirs:
    description: Testing folders per domains
    required: false
    default: "unittests"
  test-timeout:
    description: PyTest timeout
    required: false
    default: ""
  shell-type:
    description: Define Shell type
    required: false
    default: "bash"

runs:
  using: "composite"
  steps:

  - run: |
      python --version
      pip --version
      pip list
    shell: ${{ inputs.shell-type }}

  - run: |
      echo "artifact=test-results-${{ runner.os }}-py${{ inputs.python-version }}-pt{{ inputs.pytorch-version }}-${{ inputs.requires }}" >> $GITHUB_OUTPUT
    id: location
    shell: ${{ inputs.shell-type }}

  - name: Pull testing data from S3
    working-directory: ./tests
    run: |
      pip install -q "urllib3>1.0"
      # wget is simpler but does not work on Windows
      python -c "from urllib.request import urlretrieve ; urlretrieve('https://pl-public-data.s3.amazonaws.com/metrics/data.zip', 'data.zip')"
      unzip -o data.zip
      ls -l _data/*
    shell: ${{ inputs.shell-type }}

  - name: Export README tests
    run: python -m phmdoctest README.md --outfile tests/unittests/test_readme.py
    shell: ${{ inputs.shell-type }}

  - name: Unittests
    working-directory: ./tests
    run: |
      python -m pytest -v \
        ${{ inputs.dirs }} \
        --cov=torchmetrics \
        --durations=50 \
        --junitxml="${{ steps.location.outputs.artifact }}.xml" \
        ${{ inputs.test-timeout }}
    shell: ${{ inputs.shell-type }}

  - name: Upload pytest results
    uses: actions/upload-artifact@v2
    with:
      name: ${{ steps.location.outputs.artifact }}
      path: "test/${{ steps.location.outputs.artifact }}.xml"
    if: failure()

  - name: Statistics
    if: success()
    working-directory: ./tests
    run: |
      coverage xml
      coverage report
    shell: ${{ inputs.shell-type }}
