name: Compelex caching
description: some more compex caching

inputs:
  os:
    description: operation system
    required: true
  python-version:
    description: Python version
    required: true
  requires:
    description: define oldest or latest
    required: false
    default: ""
  offset:
    description: some extra hash for pip cache
    required: false
    default: ""

runs:
  using: "composite"
  steps:

  - name: PIP install assitant's deps
    run: pip install fire requests
    shell: bash

  - name: Set min. dependencies
    if: inputs.requires == 'oldest'
    run: python .github/assistant.py set-oldest-versions
    shell: bash

  - run: echo "::set-output name=period::$(python -c 'import time ; days = time.time() / 60 / 60 / 24 ; print(int(days / 7))' 2>&1)"
    if: inputs.requires == 'latest'
    id: times
    shell: bash

  # Note: This uses an internal pip API and may not always work
  # https://github.com/actions/cache/blob/master/examples.md#multiple-oss-in-a-workflow
  - name: Get pip cache
    id: pip-cache
    run: python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"
    shell: bash

  - name: Cache pip
    uses: actions/cache@v2
    with:
      path: ${{ steps.pip-cache.outputs.dir }}
      key: ${{ inputs.os }}-py${{ inputs.python-version }}-pip-td${{ steps.times.outputs.period }}-${{ inputs.offset }}-${{ hashFiles('requirements.txt') }}
      restore-keys: ${{ inputs.os }}-py${{ inputs.python-version }}-pip-td${{ steps.times.outputs.period }}-${{ inputs.offset }}-

  - name: Cache conda
    uses: actions/cache@v2
    if: inputs.os == 'Linux'
    with:
      path: ~/conda_pkgs_dir
      key: py${{ inputs.python-version }}-conda-td${{ steps.times.outputs.period }}-${{ inputs.offset }}
      restore-keys: py${{ inputs.python-version }}-conda-td${{ steps.times.outputs.period }}-${{ inputs.offset }}

  - name: HF cache
    uses: actions/cache@v2
    with:
      path: ci-cache/huggingface/
      key: cache-transformers
