name: "Build (& Push) Dockers"

on: # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - "requirements/*"
      - "requirements.txt"
      - ".devcontainer/*"
      - "dockers/**"
      - ".github/workflows/docker-build.yml"
      - "setup.py"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  PUSH_NIGHTLY: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
  PUSH_RELEASE: ${{ github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch' }}

jobs:
  build-Devcontainer:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.9"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        if: env.PUSH_RELEASE == 'true' && github.repository_owner == 'Lightning-AI'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build (and Push) Devcontainer
        # publish master/release
        uses: docker/build-push-action@v4
        with:
          build-args: |
            VARIANT=${{ matrix.python_version }}
          file: .devcontainer/Dockerfile
          push: ${{ env.PUSH_RELEASE }}
          tags: pytorchlightning/metrics-dev
        timeout-minutes: 50

  build-cuda:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # These are the base images for PL release docker images,
          # so include at least all of the combinations in release-dockers.yml.
          - { python_version: "3.9", pytorch_version: "1.13", cuda_version: "11.8.0" }
          - { python_version: "3.9", pytorch_version: "1.13", cuda_version: "12.0.1" }
          - { python_version: "3.10", pytorch_version: "2.0", cuda_version: "11.8.0" }
          - { python_version: "3.10", pytorch_version: "2.0", cuda_version: "12.0.1" }
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        if: env.PUSH_NIGHTLY == 'true' && github.repository_owner == 'Lightning-AI'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          build-args: |
            PYTHON_VERSION=${{ matrix.python_version }}
            PYTORCH_VERSION=${{ matrix.pytorch_version }}
            CUDA_VERSION=${{ matrix.cuda_version }}
          file: dockers/ubuntu-cuda/Dockerfile
          push: ${{ env.PUSH_NIGHTLY }}
          tags: "pytorchlightning/metrics-dev:ubuntu-cuda${{ matrix.cuda_version }}-py${{ matrix.python_version }}-torch${{ matrix.pytorch_version }}"
        timeout-minutes: 95
